# Generated by Django 5.2.3 on 2025-06-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_slug_alter_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_key',
            field=models.CharField(blank=True, help_text='Unique identifier for the project', max_length=50, null=True, unique=True),
        ),
    ]
