# Generated by Django 5.2.3 on 2025-06-15 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_profile_picture_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('create_project', 'Create Project'), ('manage_projects', 'Manage Projects'), ('manage_teams', 'Manage Teams'), ('view_all_tasks', 'View All Tasks'), ('assign_tasks', 'Assign Tasks'), ('create_tasks', 'Create Tasks'), ('edit_tasks', 'Edit Tasks'), ('delete_tasks', 'Delete Tasks'), ('view_reports', 'View Reports'), ('manage_users', 'Manage Users'), ('view_all_projects', 'View All Projects'), ('view_all_teams', 'View All Teams'), ('manage_labels', 'Manage Labels'), ('manage_test_cases', 'Manage Test Cases'), ('view_test_cases', 'View Test Cases'), ('manage_comments', 'Manage Comments'), ('view_comments', 'View Comments'), ('view_attachments', 'View Attachments'), ('manage_attachments', 'Manage Attachments')], max_length=50)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
