# Generated by Django 5.2.3 on 2025-06-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpermission'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='permission',
            field=models.CharField(choices=[('create_project', 'Create Project'), ('manage_projects', 'Manage Projects'), ('create_teams', 'Create Teams'), ('manage_teams', 'Manage Teams'), ('view_all_tasks', 'View All Tasks'), ('assign_tasks', 'Assign Tasks'), ('create_tasks', 'Create Tasks'), ('edit_tasks', 'Edit Tasks'), ('delete_tasks', 'Delete Tasks'), ('view_reports', 'View Reports'), ('manage_users', 'Manage Users'), ('view_all_projects', 'View All Projects'), ('view_all_teams', 'View All Teams'), ('manage_labels', 'Manage Labels'), ('manage_test_cases', 'Manage Test Cases'), ('view_test_cases', 'View Test Cases'), ('manage_comments', 'Manage Comments'), ('view_comments', 'View Comments'), ('view_attachments', 'View Attachments'), ('manage_attachments', 'Manage Attachments')], max_length=50),
        ),
    ]
