# Generated by Django 5.2.3 on 2025-06-16 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_groups_user_is_superuser_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, help_text='The user to whom this user reports directly.', limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='permission',
            field=models.CharField(choices=[('create_project', 'Create Project'), ('manage_projects', 'Manage Projects'), ('create_teams', 'Create Teams'), ('manage_teams', 'Manage Teams'), ('manage_users', 'Manage Users'), ('view_all_projects', 'View All Projects'), ('view_all_teams', 'View All Teams')], max_length=50),
        ),
    ]
