# Generated by Django 5.2.3 on 2025-06-20 07:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_testing_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
