# Generated by Django 5.2.3 on 2025-06-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_key',
            field=models.CharField(blank=True, help_text='Unique identifier for the task', max_length=50, null=True, unique=True),
        ),
    ]
